#!/bin/bash
# run/stop internet radios with PLAYER via cli

usage()
{
	echo "Usage: 
radio PATTERN   start one/multiple streams matching PATTERN
radio l         list available streams
radio q         terminate running vlc streams
	" 2>&1;
}

# reliably detect bin
pushd `dirname $0` > /dev/null
BIN=`pwd`
popd > /dev/null

PLAYERBIN='vlc';
PLAYEROPT='--qt-start-minimized --quiet';
RADIOPATH="$BIN"/radios/;

if [ ! $1 ]; then
    usage;
elif [ $1 == 'l' ]; then
        ls -1 "$RADIOPATH";
elif [ $1 == 'q' ]; then
        killall "$PLAYERBIN";
else
    # get radio
	RADIOS=$(find $RADIOPATH -type f | grep -i $1);
	
	if [ ! $RADIOS ]; then
	        echo "No radio matching $1 found" 1>&2
	else
	    killall vlc 2> /dev/null
            if hash wmctrl 2>/dev/null; then
	        cmd_in_bg "$PLAYERBIN" "$PLAYEROPT" "$RADIOS"
            else
                $PLAYERBIN $PLAYEROPT "$RADIOS" &
            fi
    fi
fi


